services:
  - type: web
    name: hamichlol-mifui-yishuvi
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_SHEETS_WEBHOOK_URL
        sync: false
